import {ArrowUpRight,FileCheck2,ShieldCheck} from 'lucide-react';
import type {Job,Outcome,Role} from './types';
import {explorer,short} from './client';
import {verifiedPayment} from './payment';

export const label=(value:string)=>value.replaceAll('_',' ').toLowerCase().replace(/^./,x=>x.toUpperCase());
export function money(value:string):string {
  const wei=BigInt(value);
  if(wei>0n&&wei<1_000_000_000_000n)return `${wei} attoGEN`;
  const whole=wei/10n**18n,rest=(wei%10n**18n).toString().padStart(18,'0').replace(/0+$/,'');
  return `${whole}${rest?'.'+rest:''} GEN`;
}
function Verdict({value}:{value:Outcome}){return <span className={`verdict ${value.toLowerCase()}`}>{label(value)}</span>;}
export function Findings({job}:{job:Job}) {
  if(!job.review)return <div className="review-placeholder"><ShieldCheck size={24}/><div><h3>{job.settlement_reason?label(job.settlement_reason):'No consensus review recorded'}</h3><p>{job.settlement_reason?'This outcome followed the agreed client/deadline rules. It is not an AI-reviewed verdict.':'Requesting a review does not mean it succeeded. Findings appear here only after successful finalized execution and evidence integrity checks.'}</p></div></div>;
  return <section className="findings" aria-labelledby="findings-title"><div className="section-heading"><div><span className="eyebrow">CONSENSUS REVIEW</span><h2 id="findings-title">Responsibility, with receipts.</h2></div><FileCheck2 className="mint"/></div><div className="outcomes">{(['A','B'] as const).map(role=><div key={role}><span className="step-square">{role}</span><span>{role==='A'?'Extraction':'Report'}</span>{job.outcomes&&<Verdict value={job.outcomes[role]}/>}</div>)}</div><p className="review-context">Each finding below is recorded by the contract. Hash checks confirm the displayed evidence matches its commitments; they do not establish real-world truth.</p>{job.review.result.assessments.map(item=><details className="finding" key={item.obligation_id} open={item.status==='VIOLATED'}><summary><span>{label(item.obligation_id)}</span><Verdict value={item.status}/></summary><p>{item.reason}</p><div className="citations">{item.citations.map((cite,i)=><blockquote key={i}><div><a href={`#job=${encodeURIComponent(job.id)}&evidence=${cite.chunk_id.split(':')[0]}`} onClick={event=>{event.preventDefault();document.getElementById(`evidence-${cite.chunk_id.split(':')[0]}`)?.scrollIntoView({block:'center'});}}>{cite.chunk_id}<ArrowUpRight size={13}/></a><span>bytes {cite.start_byte}–{cite.end_byte}</span></div><p>{cite.quote}</p><code title={cite.chunk_sha256}>Chunk hash {short(cite.chunk_sha256)}</code></blockquote>)}</div></details>)}<div className="review-meta"><span>{job.review.result.reviewed_chunks.length} ordered chunks checked</span><code title={job.review.snapshot_sha256}>Snapshot {short(job.review.snapshot_sha256)}</code></div></section>;
}
export function Payments({job}:{job:Job}) {
  return <section className="payments" aria-labelledby="payments-title"><div className="section-heading"><div><span className="eyebrow">FIXED BEFORE WORK STARTS</span><h2 id="payments-title">Work funds</h2></div><span className="meta">Received: {money(job.ledger.received)}</span></div><div className="table-scroll"><table><thead><tr><th>Participant</th><th>Fee</th><th>Bond / maximum penalty</th><th>Available credit</th><th>Transfer evidence</th></tr></thead><tbody>{(['CLIENT','A','B'] as Role[]).map(role=>{const proof=verifiedPayment(job,role);return <tr key={role}><th>{role==='CLIENT'?'Client':`Worker ${role}`}<code title={role==='CLIENT'?job.client:job.workers[role]}>{short(role==='CLIENT'?job.client:job.workers[role])}</code></th><td>{role==='CLIENT'?'—':money(job.terms.money[role].fee)}</td><td>{role==='CLIENT'?'—':`${money(job.terms.money[role].bond)} / ${money(job.terms.money[role].penalty)}`}</td><td>{money(job.ledger.credits[role])}</td><td>{proof?<><strong>Recipient transfer verified</strong><small>Exact +{money(proof.recipientBalanceDelta)} block delta</small><a href={`${explorer}/transactions/${proof.finalizationTransaction}`} target="_blank" rel="noreferrer">Finalization receipt <ArrowUpRight size={13}/></a></>:job.claims[role]?<><strong>Message emitted</strong><small>Recipient payment not verified</small></>:<span className="meta">Not requested</span>}</td></tr>;})}</tbody></table></div><p className="review-context">Unassessable work unwinds neutrally at the deadline: the client receives the fee back and the worker receives their bond. Work may remain unpaid. Credits and emitted messages are not generic payment proof; the verified release record above is bound to one finalized transaction and exact recipient balance delta.</p></section>;
}
