import {abi,createClient} from "genlayer-js";
import type {Address,CalldataEncodable,Hash} from "genlayer-js/types";
import {chain,contract,readClient,writesEnabled} from "./client";
import {readV2Deal} from "./v2-client";
import {executionName,statusName} from "../../scripts/receipts.mjs";
import type {TxRecord,Phase,Provider} from "./transactions";

export const v2HistoryKey=`tasktrace:v2:transactions:${chain.id}:${contract.toLowerCase()}`;
export const v2Pending=(record:TxRecord)=>["SIGNING","PENDING","ACCEPTED","UNKNOWN"].includes(record.phase);
export function v2History():TxRecord[]{const raw=localStorage.getItem(v2HistoryKey);if(!raw)return[];const rows:unknown=JSON.parse(raw);if(!Array.isArray(rows)||rows.some(item=>{const row=item as TxRecord;return !row||row.chainId!==chain.id||row.contract.toLowerCase()!==contract.toLowerCase()||typeof row.id!=="string"||typeof row.jobId!=="string"||typeof row.method!=="string"||!/^0x[\da-f]{40}$/i.test(row.account)||!/^\d+$/.test(row.value)||!(["SIGNING","PENDING","ACCEPTED","FINALIZED_SUCCESS","FAILED","REJECTED","UNKNOWN"] as Phase[]).includes(row.phase)}))throw new Error("Invalid v2 transaction history; inspect the wallet before submitting again");return rows as TxRecord[];}
function save(record:TxRecord){const rows=v2History(),index=rows.findIndex(item=>item.id===record.id);if(index<0)rows.unshift(record);else rows[index]=record;localStorage.setItem(v2HistoryKey,JSON.stringify(rows));window.dispatchEvent(new Event("tasktrace:v2-transactions"));}
const methods=new Set(["create_terms","fund_terms","accept_work","submit_artifact","request_review","resolve_review","advance_timeout","route_settlement","confirm_settlement"]);
function provider(){const value=(window as unknown as {ethereum?:Provider}).ethereum;if(!value?.request)throw new Error("MetaMask with the GenLayer Wallet Snap is required");return value;}
export async function submitV2(account:Address,dealId:string,method:string,args:CalldataEncodable[],value=0n){
  if(!writesEnabled)throw new Error("Writes remain locked until the verified v2 deployment is selected");
  if(!methods.has(method))throw new Error("Unsupported v2 contract action");
  if(!navigator.locks)throw new Error("Web Locks are required to prevent duplicate submissions");
  return navigator.locks.request(v2HistoryKey,{ifAvailable:true},async lock=>{if(!lock||v2History().some(v2Pending))throw new Error("Another v2 transaction is unresolved; check its existing hash before sending again");const wallet=provider(),accounts=await wallet.request({method:"eth_accounts"}) as string[];if(accounts[0]?.toLowerCase()!==account.toLowerCase())throw new Error("Wallet account changed; reconnect before signing");if(Number(await wallet.request({method:"eth_chainId"}))!==chain.id)throw new Error(`Switch the wallet to ${chain.name}`);const record:TxRecord={id:crypto.randomUUID(),jobId:dealId,method,account,chainId:chain.id,contract,value:String(value),phase:"SIGNING",createdAt:Date.now()};save(record);try{const client=createClient({chain,account,provider:wallet});record.hash=await client.writeContract({address:contract,functionName:method,args,value,leaderOnly:false,consensusMaxRotations:3});record.phase="PENDING";save(record);return record;}catch(cause){let current=cause as {code?:number;cause?:unknown};let rejected=false;for(let i=0;current&&i<5;i++){if(current.code===4001)rejected=true;current=current.cause as typeof current;}record.phase=rejected?"REJECTED":"UNKNOWN";record.error=rejected?"Signature rejected; no transaction was sent":"Submission outcome is uncertain; check wallet history and do not resend";save(record);throw new Error(record.error);}});
}
function receiptPhase(receipt:unknown):Phase{const status=statusName(receipt);if(["UNDETERMINED","CANCELED","CANCELLED","VALIDATORS_TIMEOUT","LEADER_TIMEOUT"].includes(status))return"FAILED";if(status==="FINALIZED"){const execution=executionName(receipt);return execution==="FINISHED_WITH_RETURN"?"FINALIZED_SUCCESS":execution==="FINISHED_WITH_ERROR"?"FAILED":"UNKNOWN";}return status==="ACCEPTED"?"ACCEPTED":"PENDING";}
export async function observeV2(record:TxRecord){if(!record.hash||!v2Pending(record))return record;const receipt=await readClient.getTransaction({hash:record.hash}),next={...record,phase:receiptPhase(receipt)};if(next.phase==="FINALIZED_SUCCESS"){const raw=receipt as {hash?:string;from_address?:string;to_address?:string;data?:{calldata?:{raw?:number[]}}};if(raw.hash?.toLowerCase()!==record.hash.toLowerCase()||raw.from_address?.toLowerCase()!==record.account.toLowerCase()||raw.to_address?.toLowerCase()!==contract.toLowerCase()||!Array.isArray(raw.data?.calldata?.raw))throw new Error("Finalized receipt identity does not match this v2 action");const call=abi.calldata.decode(Uint8Array.from(raw.data.calldata.raw));if(!(call instanceof Map)||call.get("method")!==record.method||!Array.isArray(call.get("args"))||(call.get("args") as unknown[])[0]!==record.jobId)throw new Error("Finalized receipt belongs to another v2 operation");const deal=await readV2Deal(record.jobId);const role=deal.manifest.client.toLowerCase()===record.account.toLowerCase()?"CLIENT":(["A","B"] as const).find(item=>deal.manifest.terms.workers[item].toLowerCase()===record.account.toLowerCase());const legId=String((call.get("args") as unknown[])[1]??"");const leg=deal.settlement_legs.find(item=>item.id===legId);const matched=record.method==="create_terms"?role==="CLIENT":record.method==="fund_terms"?deal.status!=="DRAFT_UNFUNDED":record.method==="accept_work"?Boolean(role&&role!=="CLIENT"&&deal.accepted[role]):record.method==="submit_artifact"?Boolean(role&&role!=="CLIENT"&&deal.artifacts[role]?.issuer.toLowerCase()===record.account.toLowerCase()):record.method==="request_review"?Boolean(deal.adjudication_deadline):record.method==="resolve_review"?Boolean(deal.report):record.method==="advance_timeout"?deal.status==="SETTLEMENT_PENDING":record.method==="route_settlement"?Boolean(leg&&["ROUTED","CONFIRMED"].includes(leg.state)):record.method==="confirm_settlement"?leg?.state==="CONFIRMED":false;if(!matched)throw new Error("Transaction finalized but expected v2 contract state is not observable");}if(next.phase==="FAILED")next.error=`${statusName(receipt)} / ${executionName(receipt)}; successful execution was not proven`;save(next);return next;}
