import {useEffect,useState,type FormEvent} from "react";
import {createPublicClient,getContract,http,parseUnits} from "viem";
import type {Address,CalldataEncodable} from "genlayer-js/types";
import {chain} from "./client";
import {githubCommitment,githubOrigin} from "./v2-evidence";
import {submitV2} from "./v2-transactions";
import {friendlyError} from "./errors";
import {observeRouter,releaseRouterReceipt,routerAbi,routerHistory,type RouterRecord} from "./v2-router";
import type {V2Deal,V2Role} from "./v2-types";

const rawAmount=(value:string)=>{if(!/^\d+(?:\.\d{1,18})?$/.test(value))throw new Error("Use a non-negative GEN amount with at most 18 decimals");const amount=parseUnits(value,18);if(amount<=0n||amount>100n*10n**18n)throw new Error("Use an amount above zero and at most 100 GEN");return amount;};
const roleOf=(deal:V2Deal,account?:string):V2Role|undefined=>{if(!account)return;if(deal.manifest.client.toLowerCase()===account.toLowerCase())return"CLIENT";for(const role of ["A","B"] as const)if(deal.manifest.terms.workers[role].toLowerCase()===account.toLowerCase())return role;};
const deadline=(deal:V2Deal)=>({FUNDED:deal.accept_deadline,ACTIVE_A:deal.a_deadline,ACTIVE_B:deal.b_deadline,REVIEWABLE:deal.review_deadline,REVIEW_REQUESTED:deal.adjudication_deadline,INCONCLUSIVE:deal.adjudication_deadline} as Record<string,number|undefined>)[deal.status];

export function V2Actions({deal,account,busy,onSubmitted}:{deal:V2Deal;account?:Address;busy:boolean;onSubmitted:()=>void}){
  const [error,setError]=useState(""),[signing,setSigning]=useState(false),[commit,setCommit]=useState(""),[path,setPath]=useState("");
  const [receiptStates,setReceiptStates]=useState<Record<string,number>>({}),[routerRecords,setRouterRecords]=useState<RouterRecord[]>([]);
  const [now,setNow]=useState(Date.now()/1000);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{let live=true;const routed=deal.settlement_legs.filter(leg=>leg.state==="ROUTED");try{setRouterRecords(routerHistory(deal.router));}catch(cause){setError(friendlyError(cause,"Receipt journal unavailable"));}if(!routed.length){setReceiptStates({});return;}const publicClient=createPublicClient({chain,transport:http(chain.rpcUrls.default.http[0])}),router=getContract({address:deal.router as Address,abi:routerAbi,client:publicClient});void observeRouter(deal.router).then(rows=>{if(live)setRouterRecords(rows);});void Promise.all(routed.map(async leg=>[leg.receipt_id,Number(await router.read.receiptState([`0x${leg.receipt_id}`]))] as const)).then(rows=>{if(live)setReceiptStates(Object.fromEntries(rows));}).catch(cause=>{if(live)setError(friendlyError(cause,"Could not verify router receipts"));});return()=>{live=false;};},[deal.router,deal.settlement_legs]);
  const role=roleOf(deal,account),due=deadline(deal),expired=due!==undefined&&now>=due;
  async function send(method:string,args:CalldataEncodable[]=[deal.deal_id],value=0n){if(!account||signing)return;setSigning(true);setError("");try{await submitV2(account,deal.deal_id,method,args,value);onSubmitted();}catch(cause){setError(friendlyError(cause,"Transaction failed"));}finally{setSigning(false);}}
  async function submitArtifact(event:FormEvent){event.preventDefault();if(role!=="A"&&role!=="B")return;setSigning(true);setError("");try{const origin=deal.manifest.terms.origins[role],commitment=await githubCommitment(origin.owner,origin.repository,commit,path);if(JSON.stringify(commitment.origin)!==JSON.stringify(origin))throw new Error("GitHub repository identity differs from frozen terms");const upstream=deal.artifacts[role==="A"?"SOURCE":"A"]?.submission_id;if(!upstream)throw new Error("Upstream artifact is not finalized");await submitV2(account!,deal.deal_id,"submit_artifact",[deal.deal_id,JSON.stringify(commitment),upstream]);setCommit("");setPath("");onSubmitted();}catch(cause){setError(cause instanceof Error?cause.message:"Artifact commitment failed");}finally{setSigning(false);}}
  async function release(receiptId:string){if(!account)return;setSigning(true);setError("");try{const record=await releaseRouterReceipt(deal.router as Address,account,deal.deal_id,receiptId);setRouterRecords(routerHistory(deal.router));if(record.phase==="FINALIZED_SUCCESS")setReceiptStates(current=>({...current,[receiptId]:2}));onSubmitted();}catch(cause){setRouterRecords(routerHistory(deal.router));setError(friendlyError(cause,"Receipt release failed"));}finally{setSigning(false);}}
  return <section className="v2-actions"><header><div><span className="eyebrow">NEXT CONTRACT ACTION</span><h2>{role?`Connected as ${role==="CLIENT"?"client":`worker ${role}`}`:"Connect a participant wallet"}</h2></div>{due&&<span className={expired?"deadline expired":"deadline"}>{expired?"Deadline reached":"Due"} · {new Date(due*1000).toLocaleString()}</span>}</header>{error&&<p className="error">{error}</p>}<fieldset disabled={!account||busy||signing}>
    {deal.status==="DRAFT_UNFUNDED"&&role==="CLIENT"&&<button className="primary" onClick={()=>void send("fund_terms",[deal.deal_id,deal.terms_hash],(["A","B"] as const).reduce((sum,item)=>sum+BigInt(deal.manifest.terms.money[item].fee),0n))}>Fund exact worker fees</button>}
    {deal.status==="FUNDED"&&(role==="A"||role==="B")&&!deal.accepted[role]&&!expired&&<button className="primary" onClick={()=>void send("accept_work",[deal.deal_id,deal.terms_hash],BigInt(deal.manifest.terms.money[role].bond))}>Accept exact terms & bond</button>}
    {!expired&&((deal.status==="ACTIVE_A"&&role==="A")||(deal.status==="ACTIVE_B"&&role==="B"))&&<form onSubmit={event=>void submitArtifact(event)}><p>The repository identity is frozen as <strong>{deal.manifest.terms.origins[role].owner}/{deal.manifest.terms.origins[role].repository}</strong>. The contract—not this form—independently re-fetches and verifies the complete file.</p><label>Immutable 40-character commit SHA<input required value={commit} onChange={event=>setCommit(event.target.value)} pattern="[0-9a-fA-F]{40}"/></label><label>Artifact path<input required value={path} onChange={event=>setPath(event.target.value)} placeholder="evidence/final.txt"/></label><button className="primary">Verify locally & submit commitment</button></form>}
    {deal.status==="REVIEWABLE"&&role&&!expired&&<button className="primary" onClick={()=>void send("request_review")}>Freeze evidence manifest</button>}
    {deal.status==="REVIEW_REQUESTED"&&role&&!expired&&<button className="primary" onClick={()=>void send("resolve_review")}>Run independent validator review</button>}
    {expired&&due&&role&&<button className="primary" onClick={()=>void send("advance_timeout")}>Apply frozen timeout rule</button>}
    {deal.status==="SETTLEMENT_PENDING"&&role&&<div className="settlement-actions">{deal.settlement_legs.map(leg=><article key={leg.id}><div><strong>{leg.id}</strong><small>{leg.amount} attoGEN · {leg.state}{leg.state==="ROUTED"?` · router ${receiptStates[leg.receipt_id]===2?"released":receiptStates[leg.receipt_id]===1?"funded":"checking"}`:""}</small></div>{leg.state==="ELIGIBLE"&&<button onClick={()=>void send("route_settlement",[deal.deal_id,leg.id])}>Route exact leg</button>}{leg.state==="ROUTED"&&receiptStates[leg.receipt_id]===1&&leg.recipient.toLowerCase()===account?.toLowerCase()&&<button onClick={()=>void release(leg.receipt_id)}>Release receipt</button>}{leg.state==="ROUTED"&&receiptStates[leg.receipt_id]===2&&<button onClick={()=>void send("confirm_settlement",[deal.deal_id,leg.id])}>Confirm released receipt</button>}</article>)}</div>}
  </fieldset>{routerRecords.filter(item=>item.dealId===deal.deal_id).slice(0,3).map(item=><p className="router-journal" key={item.id}>Receipt release · <code>{item.hash??"awaiting wallet"}</code> · {item.phase.replaceAll("_"," ")}</p>)}</section>;
}

export function V2NewDeal({account,onClose,onSubmitted}:{account?:Address;onClose:()=>void;onSubmitted:(id:string)=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!account||busy)return;setBusy(true);setError("");try{const form=new FormData(event.currentTarget),value=(name:string)=>String(form.get(name)??"").trim();const dealId=value("dealId"),workerA=value("workerA"),workerB=value("workerB");if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(dealId))throw new Error("Deal ID must use lowercase letters, numbers and hyphens");if(!/^0x[\da-fA-F]{40}$/.test(workerA)||!/^0x[\da-fA-F]{40}$/.test(workerB)||new Set([account.toLowerCase(),workerA.toLowerCase(),workerB.toLowerCase()]).size!==3)throw new Error("Client and both workers must be distinct valid addresses");const source=await githubCommitment(value("sourceOwner"),value("sourceRepo"),value("sourceCommit"),value("sourcePath")),originA=await githubOrigin(value("aOwner"),value("aRepo")),originB=await githubOrigin(value("bOwner"),value("bRepo"));const feeA=rawAmount(value("feeA")),feeB=rawAmount(value("feeB")),bondA=rawAmount(value("bondA")),bondB=rawAmount(value("bondB")),penaltyA=rawAmount(value("penaltyA")),penaltyB=rawAmount(value("penaltyB"));if(penaltyA>bondA||penaltyB>bondB)throw new Error("A penalty cannot exceed its worker bond");const terms={workers:{A:workerA,B:workerB},origins:{SOURCE:source.origin,A:originA,B:originB},source,money:{A:{fee:String(feeA),bond:String(bondA),penalty:String(penaltyA)},B:{fee:String(feeB),bond:String(bondB),penalty:String(penaltyB)}},windows:{accept:Number(value("acceptHours"))*3600,step:Number(value("stepHours"))*3600,review:Number(value("reviewHours"))*3600,adjudication:Number(value("adjudicationHours"))*3600},max_revisions:0,semantic_obligations:[{id:"SEM_A_SCOPE_ACCURACY",stage:"A",statement:value("obligationA"),evidence_ids:["SOURCE","A"]},{id:"SEM_B_FAITHFUL_HANDOFF",stage:"B",statement:value("obligationB"),evidence_ids:["A","B"]}]};for(const seconds of Object.values(terms.windows))if(!Number.isInteger(seconds)||seconds<60||seconds>30*86400)throw new Error("Every window must be between one minute and 30 days");await submitV2(account,dealId,"create_terms",[dealId,JSON.stringify(terms)]);onSubmitted(dealId);}catch(cause){setError(friendlyError(cause,"Could not create v2 deal"));}finally{setBusy(false);}}
  return <section className="new-job v2-new"><div className="section-heading"><div><span className="eyebrow">NEW V2 EVIDENCE DEAL</span><h2>Freeze every material promise first.</h2></div><button onClick={onClose}>Close</button></div>{error&&<p className="error">{error}</p>}<form onSubmit={event=>void create(event)}><fieldset disabled={!account||busy}><div className="form-grid"><label>Deal ID<input name="dealId" required defaultValue={`evidence-${crypto.randomUUID().slice(0,8)}`}/></label><label>Worker A wallet<input name="workerA" required placeholder="0x…"/></label><label>Worker B wallet<input name="workerB" required placeholder="0x…"/></label></div><h3>Immutable source</h3><div className="form-grid"><label>Source owner<input name="sourceOwner" required defaultValue="tanphung"/></label><label>Source repository<input name="sourceRepo" required defaultValue="tasktrace"/></label><label>Source commit<input name="sourceCommit" required pattern="[0-9a-fA-F]{40}"/></label><label>Source path<input name="sourcePath" required placeholder="evidence/source.md"/></label></div><h3>Worker evidence origins</h3><div className="form-grid"><label>A GitHub owner<input name="aOwner" required defaultValue="tanphung"/></label><label>A repository<input name="aRepo" required defaultValue="tasktrace"/></label><label>B GitHub owner<input name="bOwner" required defaultValue="tanphung"/></label><label>B repository<input name="bRepo" required defaultValue="tasktrace"/></label></div><h3>Exact semantic obligations</h3><label>Stage A duty<textarea name="obligationA" required defaultValue="Stage A must preserve every material condition, restriction and exception in the complete source artifact."/></label><label>Stage B duty<textarea name="obligationB" required defaultValue="Stage B must faithfully preserve Stage A's complete output without weakening, contradicting or inventing material claims."/></label><h3>Money and windows</h3><div className="form-grid compact">{(["A","B"] as const).flatMap(role=>(["fee","bond","penalty"] as const).map(kind=><label key={`${role}-${kind}`}>{role} {kind} (GEN)<input name={`${kind}${role}`} required defaultValue={kind==="fee"?"0.01":kind==="bond"?"0.005":"0.003"}/></label>))}<label>Accept hours<input name="acceptHours" type="number" min="1" max="720" defaultValue="24"/></label><label>Step hours<input name="stepHours" type="number" min="1" max="720" defaultValue="24"/></label><label>Review hours<input name="reviewHours" type="number" min="1" max="720" defaultValue="24"/></label><label>Adjudication hours<input name="adjudicationHours" type="number" min="1" max="720" defaultValue="24"/></label></div><label className="check"><input type="checkbox" required/>I understand all terms, identities, deadlines and settlement formulas become immutable contract state.</label><button className="primary" disabled={!account}>{account?"Create frozen terms":"Connect client wallet first"}</button></fieldset></form></section>;
}
