import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowUpRight,CheckCircle2,FileKey2,Layers3,Plus,RefreshCw,Route,ShieldCheck,Wallet} from "lucide-react";
import type {Address} from "genlayer-js/types";
import {chain,contract,explorer,jobHref,short} from "./client";
import {connect,watchWallet} from "./transactions";
import {listV2Deals,readV2Deal} from "./v2-client";
import {V2Report} from "./V2Report";
import {V2Actions,V2NewDeal} from "./V2Actions";
import {observeV2,v2History,v2Pending} from "./v2-transactions";
import type {TxRecord} from "./transactions";
import type {V2Deal} from "./v2-types";

const selectedFromUrl=()=>new URLSearchParams(location.hash.slice(1)).get("job")??"";
const lifecycle=["Terms frozen","Fees funded","Workers bonded","Artifacts committed","Committee review","Receipt release"];

export default function V2App(){
  const [ids,setIds]=useState<string[]>([]),[deal,setDeal]=useState<V2Deal>();
  const [selected,setSelected]=useState(selectedFromUrl),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [account,setAccount]=useState<Address>(),[connecting,setConnecting]=useState(false),[walletError,setWalletError]=useState("");
  const [creating,setCreating]=useState(false),[records,setRecords]=useState<TxRecord[]>([]),[historyError,setHistoryError]=useState("");
  const generation=useRef(0),observing=useRef(false);
  const refresh=useCallback(async()=>{const turn=++generation.current;setLoading(true);setError("");try{const found=await listV2Deals();if(turn!==generation.current)return;setIds(found);const id=selected||found[0];if(!id){setDeal(undefined);return;}const value=await readV2Deal(id);if(turn!==generation.current)return;setDeal(value);if(!selected){location.hash=jobHref(id);setSelected(id);}}catch(cause){if(turn===generation.current){setDeal(undefined);setError(cause instanceof Error?cause.message:"Unable to read v2 contract state");}}finally{if(turn===generation.current)setLoading(false);}},[selected]);
  useEffect(()=>{void refresh();return()=>{generation.current++;};},[refresh]);
  useEffect(()=>{const change=()=>{const id=selectedFromUrl();if(id===selected)return;setSelected(id);setDeal(undefined);};window.addEventListener("hashchange",change);return()=>window.removeEventListener("hashchange",change);},[selected]);
  useEffect(()=>{if(!account)return;return watchWallet(()=>{setAccount(undefined);setWalletError("Wallet or network changed. Reconnect before signing.");});},[account]);
  const loadHistory=useCallback(()=>{try{setRecords(v2History());setHistoryError("");}catch(cause){setHistoryError(cause instanceof Error?cause.message:"V2 transaction tracking unavailable");}},[]);
  useEffect(()=>{loadHistory();window.addEventListener("tasktrace:v2-transactions",loadHistory);return()=>window.removeEventListener("tasktrace:v2-transactions",loadHistory);},[loadHistory]);
  const checkTransactions=useCallback(async()=>{if(observing.current)return;observing.current=true;try{for(const record of v2History().filter(v2Pending)){const result=await observeV2(record);if(result.phase==="FINALIZED_SUCCESS")await refresh();}}catch(cause){setHistoryError(cause instanceof Error?cause.message:"Could not observe v2 transaction");}finally{observing.current=false;}},[refresh]);
  useEffect(()=>{void checkTransactions();const timer=setInterval(()=>void checkTransactions(),8000);return()=>clearInterval(timer);},[checkTransactions]);
  async function connectWallet(){setConnecting(true);setWalletError("");try{setAccount(await connect());}catch(cause){setWalletError(cause instanceof Error?cause.message:"Wallet connection failed");}finally{setConnecting(false);}}
  const stage=deal?["DRAFT_UNFUNDED","FUNDED","ACTIVE_A","ACTIVE_B","REVIEWABLE","REVIEW_REQUESTED","INCONCLUSIVE","SETTLEMENT_PENDING","COMPLETED"].indexOf(deal.status):-1;
  const verified=deal?.report?.source_assessments.length??0;
  const assessed=deal?.report?.obligation_assessments.length??0;
  const busy=records.some(v2Pending)||Boolean(historyError);
  return <div className="app-shell v2-shell"><aside className="sidebar"><a className="brand" href="#"><img src="/icon.svg" alt=""/><span>TaskTrace<span className="brand-dot">.</span></span></a><div className="sidebar-label">INTELLIGENT CONTRACT V2</div><a className="nav-item active" href="#"><Layers3 size={18}/> Evidence deals <span>{ids.length}</span></a><div className="sidebar-label jobs-label">FINALIZED DEALS</div><nav>{ids.map(id=><a className={`job-link ${selected===id?"selected":""}`} href={jobHref(id)} key={id}><span className="tiny-dot"/>{id.replaceAll("-"," ")}</a>)}</nav><div className="sidebar-bottom"><ShieldCheck/><p>Exact obligations.<br/><strong>Independent validators.</strong></p><a href={`${explorer}/contracts/${contract}`} target="_blank" rel="noreferrer">Inspect contract <ArrowUpRight size={13}/></a></div></aside>
    <main className="main"><header className="topbar"><span className="breadcrumb">Protocol <span>/</span> Evidence settlement</span><div className="button-row"><span className="network"><span className="tiny-dot"/>{chain.name}</span><button className="wallet-button" onClick={()=>void connectWallet()} disabled={connecting}><Wallet size={16}/>{connecting?"Connecting…":account?short(account):"Connect wallet"}</button></div></header><div className="content v2-content">
      <section className="hero-stage v2-hero"><div className="page-heading"><div className="hero-copy"><span className="eyebrow">VERIFIABLE HUMAN + AGENT HANDOFFS</span><h1>Evidence in.<span>Receipts out.</span></h1><p>GenLayer validators independently re-fetch complete immutable artifacts, assess every frozen obligation and authorize exact settlement legs.</p><div className="hero-actions"><a className="primary" href="#obligations">Inspect obligations</a><a className="secondary-link" href="#settlement">Follow settlement <Route size={16}/></a></div></div></div><div className="hero-proof"><span><span className="proof-pulse"/> INTELLIGENT CONTRACT</span><strong>Decision logic on-chain</strong><small>No backend verdict · no UI settlement logic</small></div><div className="hero-motes"><i/><i/><i/></div></section>
      <section className="v2-metrics"><article><FileKey2/><div><span>Frozen obligations</span><strong>{deal?.manifest.obligations.length??"—"}</strong></div></article><article><CheckCircle2/><div><span>Sources verified</span><strong>{verified}/3</strong></div></article><article><ShieldCheck/><div><span>Assessments</span><strong>{assessed||"—"}</strong></div></article><article><Route/><div><span>Settlement proof</span><strong>{deal?.settlement_legs.filter(item=>item.state==="CONFIRMED").length??0}/{deal?.settlement_legs.length??0}</strong></div></article></section>
      <section className="v2-lifecycle"><div><span className="eyebrow">DETERMINISTIC LIFECYCLE</span><h2>{deal?deal.status.replaceAll("_"," "):"Waiting for finalized state"}</h2></div><ol>{lifecycle.map((item,index)=><li className={stage>=index?"done":stage===index-1?"current":""} key={item}><span>{stage>=index?<CheckCircle2/>:index+1}</span><strong>{item}</strong></li>)}</ol></section>
      {walletError&&<p className="error">{walletError}</p>}{historyError&&<p className="error">{historyError}</p>}{error&&<p className="error">{error}<button onClick={()=>void refresh()}>Retry</button></p>}
      {!!records.length&&<section className="transaction-panel"><div className="section-heading"><div><span className="eyebrow">LOCAL SAFETY JOURNAL</span><h2>Existing transaction hashes</h2></div><button onClick={()=>void checkTransactions()}>Check same hashes</button></div>{records.slice(0,8).map(record=><div className="transaction" key={record.id}><div><strong>{record.method.replaceAll("_"," ")}</strong><span className="meta">{record.jobId}</span></div><span className={`verdict ${record.phase==="FINALIZED_SUCCESS"?"satisfied":record.phase==="FAILED"?"violated":""}`}>{record.phase.replaceAll("_"," ")}</span>{record.hash?<a href={`${explorer}/transactions/${record.hash}`} target="_blank" rel="noreferrer"><code>{short(record.hash)}</code><ArrowUpRight size={13}/></a>:<span className="meta">Check wallet before retrying</span>}</div>)}</section>}
      <div className="v2-create-row"><button className="primary" onClick={()=>setCreating(value=>!value)} disabled={busy}><Plus size={16}/>{creating?"Return to deal":"New evidence deal"}</button></div>
      {creating?<V2NewDeal account={account} onClose={()=>setCreating(false)} onSubmitted={id=>{loadHistory();location.hash=jobHref(id);setSelected(id);setCreating(false);}}/>:<section className="workspace v2-workspace"><div className="section-heading"><div><span className="eyebrow">FINALIZED CONTRACT STATE</span><h2>{deal?.deal_id??"Evidence deals"}</h2></div><button className="icon-button" aria-label="Refresh finalized contract state" onClick={()=>void refresh()} disabled={loading}><RefreshCw className={loading?"spinning":""}/></button></div>{!deal&&!error&&<p className="empty">{loading?"Reading v2 Intelligent Contract…":"No finalized v2 deal yet."}</p>}{deal&&<><div className="v2-identity"><span className="status">{deal.status.replaceAll("_"," ")}</span><code>{deal.deal_id}</code><span>Terms {short(deal.terms_hash)}</span><span>Router {short(deal.router)}</span></div><V2Actions deal={deal} account={account} busy={busy} onSubmitted={loadHistory}/><V2Report deal={deal}/></>}</section>}
      <footer className="page-footer"><span>TaskTrace v2 / Future of Work</span><a href="https://github.com/tanphung/tasktrace" target="_blank" rel="noreferrer">Contract, tests & evidence <ArrowUpRight size={13}/></a></footer>
    </div></main></div>;
}
